{
 "title": "PowerFlex - 2. Devices",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster\""
   },
   {
    "name": "domain",
    "query": "SHOW TAG VALUES FROM \"scaleio.protectiondomain.iops.read\" WITH KEY = \"protection_domain_name\" WHERE \"cluster\" =~ /^$cluster$/"
   },
   {
    "name": "pool",
    "query": "SHOW TAG VALUES FROM \"scaleio.storagepool\" WITH KEY = \"storage_pool_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/"
   },
   {
    "name": "sds",
    "label": "sds",
    "query": "SHOW TAG VALUES FROM \"scaleio.device\" WITH KEY = \"sds\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/"
   },
   {
    "name": "device",
    "query": "SHOW TAG VALUES FROM \"scaleio.device\" WITH KEY = \"device_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"sds\" =~ /^$sds$/"
   },
   {
    "name": "devicepath",
    "query": "SHOW TAG VALUES FROM \"scaleio.device\" WITH KEY = \"device_path\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/ AND \"sds\" =~ /^$sds$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>Device Statistics:</b></h2> <h3><b>Cluster = $cluster</b></h3> <h3><b>SDS = $sds</h3></br> <h3>Metrics as reported by PowerFlex</h3></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Read IOPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": false,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.iops.read",
     "metric": "scaleio.device.iops.read_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Write IOPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": false,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.iops.write",
     "metric": "scaleio.device.iops.write_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Read B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": false,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.bw.read",
     "metric": "scaleio.device.bw.read_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Write B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": false,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.bw.write",
     "metric": "scaleio.device.bw.write_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Read Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": false,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device",
     "metric": "scaleio.device_avgReadLatencyInMicrosec",
     "select": [
      [
       { "params": [ "avgReadLatencyInMicrosec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Write Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": false,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device",
     "metric": "scaleio.device_avgWriteLatencyInMicrosec",
     "select": [
      [
       { "params": [ "avgWriteLatencyInMicrosec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency for $device Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device",
     "metric": "scaleio.device_avgReadLatencyInMicrosec",
     "select": [
      [
       { "params": [ "avgReadLatencyInMicrosec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency for $device Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device",
     "metric": "scaleio.device_avgWriteLatencyInMicrosec",
     "select": [
      [
       { "params": [ "avgWriteLatencyInMicrosec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Read IOPS per Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.iops.read",
     "metric": "scaleio.device.iops.read_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Write IOPS per Disk (Total w/ secondary write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.iops.write",
     "metric": "scaleio.device.iops.write_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Bandwidth per Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.bw.read",
     "metric": "scaleio.device.bw.read_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Bandwidth per Disk (Total w/ secondary write)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.bw.write",
     "metric": "scaleio.device.bw.write_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Read IO Size per Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.iosize.read",
     "metric": "scaleio.device.bw.read_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Write IO Size per Disk",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_sds $tag_device_name ($tag_device_path)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$sds",
       "groupBy": false,
       "tagk": "sds",
       "type": "literal_or"
      },
      {
       "filter": "$device",
       "groupBy": true,
       "tagk": "device_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "device_path" ], "type": "tag" },
      { "params": [ "sds" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device.iosize.write",
     "metric": "scaleio.device.bw.write_total",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" },
      { "condition": "AND", "key": "sds", "operator": "=~", "value": "/^$sds$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  }
 ]
}