{
 "title": "PowerFlex - 3. Pools",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster\""
   },
   {
    "name": "clusterid",
    "query": "SHOW TAG VALUES FROM \"scaleio.cluster\" WITH KEY = \"cluster_id\""
   },
   {
    "name": "domain",
    "query": "SHOW TAG VALUES FROM \"scaleio.protectiondomain.iops.read\" WITH KEY = \"protection_domain_name\" WHERE \"cluster\" =~ /^$cluster$/"
   },
   {
    "name": "domainid",
    "query": "SHOW TAG VALUES FROM \"scaleio.protectiondomain.iops.read\" WITH KEY = \"protection_domain_id\" WHERE \"cluster\" =~ /^$cluster$/ "
   },
   {
    "name": "pool",
    "query": "SHOW TAG VALUES FROM \"scaleio.storagepool\" WITH KEY = \"storage_pool_name\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/"
   },
   {
    "name": "poolid",
    "query": "SHOW TAG VALUES FROM \"scaleio.storagepool\" WITH KEY = \"storage_pool_id\" WHERE \"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2><b>Storage pool statistics</b> : $cluster / $domain / $pool</h2></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_capacityInUseInKb",
     "select": [
      [
       { "params": [ "capacityInUseInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Net Capacity Metrics for: $pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Used",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_capacityInUseInKb",
     "select": [
      [
       { "params": [ "capacityInUseInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Spare",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "select": [
      [
       { "params": [ "spareCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Unused",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_unusedCapacityInKb",
     "select": [
      [
       { "params": [ "unusedCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Capacity in Use (no overhead)",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_degradedFailedCapacityInKb",
     "select": [
      [
       { "params": [ "netCapacityInUseNoOverheadInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Snapshot Capacity",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "query": "SELECT mean(\"netSnapshotCapacityInKb\")  / 2 FROM \"scaleio.storagepool\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"protection_domain_name\" =~ /^$domain$/ AND \"storage_pool_name\" =~ /^$pool$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "netSnapshotCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Allocated Thin Capacity",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "select": [
      [
       { "params": [ "thinCapacityAllocatedInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Thin Capacity in Use",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "select": [
      [
       { "params": [ "netThinUserDataCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Thick Capacity in Use",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "select": [
      [
       { "params": [ "thickCapacityInUseInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "MG User Data",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_failedCapacityInKb",
     "select": [
      [
       { "params": [ "netMgUserDataCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "FG User Data",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_failedCapacityInKb",
     "select": [
      [
       { "params": [ "netFglUserDataCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "FG Spares",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "select": [
      [
       { "params": [ "netFglSparesInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "sum",
     "alias": "Metadata",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$poolid",
       "groupBy": false,
       "tagk": "storage_pool_id",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_spareCapacityInKb",
     "select": [
      [
       { "params": [ "netMetadataOverheadInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool",
     "metric": "scaleio.storagepool_capacityAvailableForVolumeAllocationInKb",
     "select": [
      [
       { "params": [ "unusedCapacityInKb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Read IOPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.iops.read",
     "metric": "scaleio.storagepool.iops.read_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Write IOPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.iops.write",
     "metric": "scaleio.storagepool.iops.write_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Read B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.bw.read",
     "metric": "scaleio.storagepool.bw.read_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Write B/W",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.bw.write",
     "metric": "scaleio.storagepool.bw.write_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Pool IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Read IOPS",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.iops.read",
     "metric": "scaleio.storagepool.iops.read_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "Write IOPS",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.iops.write",
     "metric": "scaleio.storagepool.iops.write_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Pool Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Read BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.bw.read",
     "metric": "scaleio.storagepool.bw.read_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "aggregator": "avg",
     "alias": "Write BW",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "$pool",
       "groupBy": false,
       "tagk": "storage_pool_name",
       "type": "literal_or"
      },
      {
       "filter": "$domain",
       "groupBy": false,
       "tagk": "protection_domain_name",
       "type": "literal_or"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.storagepool.bw.write",
     "metric": "scaleio.storagepool.bw.write_total",
     "select": [
      [
       { "params": [ "primary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "protection_domain_name", "operator": "=~", "value": "/^$domain$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Device Read Latency (per Pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_protection_domain_name / $tag_storage_pool_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "protection_domain_name",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "storage_pool_name",
       "type": "wildcard"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protection_domain_name" ], "type": "tag" },
      { "params": [ "storage_pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device",
     "metric": "scaleio.device_avgReadLatencyInMicrosec",
     "select": [
      [
       { "params": [ "avgReadLatencyInMicrosec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Device Write Latency (per Pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_protection_domain_name / $tag_storage_pool_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$cluster",
       "groupBy": false,
       "tagk": "cluster",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "protection_domain_name",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "storage_pool_name",
       "type": "wildcard"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protection_domain_name" ], "type": "tag" },
      { "params": [ "storage_pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scaleio.device",
     "metric": "scaleio.device_avgWriteLatencyInMicrosec",
     "select": [
      [
       { "params": [ "avgWriteLatencyInMicrosec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "storage_pool_name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  }
 ]
}